---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    provider: fabric8
    project: TicketBooking
    version: 1.0-SNAPSHOT
    group: Paytm
  name: ticketbooking
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: TicketBooking
    provider: fabric8
    group: Paytm
